-- SELECT CURRENT_DATE(); -- GIVE CURRENT DATE

-- SELECT CURRENT_TIME(); -- GIVE CURRENT TIME

-- SELECT CURRENT_TIMESTAMP(); -- GIVE CURRENT TIME AND DATE BOTH
-- SELECT NOW(); -- GIVE CURRENT TIME AND DATE BOTH

-- SELECT DATE_ADD(CURRENT_DATE,INTERVAL 10 DAY); -- ADD IN DATE
-- SELECT DATE_ADD(DATE_ADD("2005-10-30",INTERVAL 20 YEAR),INTERVAL 11 DAY);

-- SELECT DATE_SUB(CURRENT_DATE(),INTERVAL 7 MONTH); -- SUBTRACT FROM DATE

-- SELECT EXTRACT(YEAR FROM "1997-06-23") AS EXTRACTED_YEAR;
-- SELECT EXTRACT(MONTH FROM "1395-05-14") AS EXTRACTED_MONTH;

-- BELOW ONE RETURN NUMBER OF DAYS.
-- SELECT DATEDIFF(CURRENT_DATE(),"1993-04-23"); -- Find how many days are between two dates by subtracting.

-- SELECT LAST_DAY(CURRENT_DATE()); -- GIVE LAST DATE OF MONTH OF GIVEN DATE